// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuT2aLjdyustJroFbOpNlX0vZ528sy5tc',
    appId: '1:179930761818:web:165ab271b7ff6cd7e1a663',
    messagingSenderId: '179930761818',
    projectId: 'smart-tns',
    authDomain: 'smart-tns.firebaseapp.com',
    storageBucket: 'smart-tns.firebasestorage.app',
    measurementId: 'G-E9DPM145PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGcrPWMLVRUXMN_cz30_WU8cD3LMmn7yc',
    appId: '1:179930761818:android:86a44f564b597f18e1a663',
    messagingSenderId: '179930761818',
    projectId: 'smart-tns',
    storageBucket: 'smart-tns.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByTmzPRS2tnV0ItfY-I382lsHRw1p8PsM',
    appId: '1:179930761818:ios:dad7be2f535b9027e1a663',
    messagingSenderId: '179930761818',
    projectId: 'smart-tns',
    storageBucket: 'smart-tns.firebasestorage.app',
    iosClientId: '179930761818-npshh8dte2b6cvopri93374fefhgslnc.apps.googleusercontent.com',
    iosBundleId: 'com.example.unicalhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByTmzPRS2tnV0ItfY-I382lsHRw1p8PsM',
    appId: '1:179930761818:ios:dad7be2f535b9027e1a663',
    messagingSenderId: '179930761818',
    projectId: 'smart-tns',
    storageBucket: 'smart-tns.firebasestorage.app',
    iosClientId: '179930761818-npshh8dte2b6cvopri93374fefhgslnc.apps.googleusercontent.com',
    iosBundleId: 'com.example.unicalhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdbnRzz6ZRhgX9BgWflSjdj1feCB8jYvA',
    appId: '1:179930761818:web:04ba15450467408ce1a663',
    messagingSenderId: '179930761818',
    projectId: 'smart-tns',
    authDomain: 'smart-tns.firebaseapp.com',
    storageBucket: 'smart-tns.firebasestorage.app',
    measurementId: 'G-2WLF0MDWP2',
  );
}
